replicaCount: 1

image:
  repository: nishanttdevops/grafana-image-renderer
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
