apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    app: grafana
spec:
  type: {{ .Values.service.type }}
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
