annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/grafana/helm-charts
    - name: Upstream Project
      url: https://github.com/grafana/mcp-grafana
apiVersion: v2
appVersion: latest
description: MCP server for Grafana.
home: https://grafana.com
icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
keywords:
- monitoring
- mcp
kubeVersion: ^1.8.0-0
maintainers:
- email: sheikhabubaker761@gmail.com
  name: Sheikh-Abubaker
- email: github@jkroepke.de
  name: jkroepke
- email: avivguiser@gmail.com
  name: KyriosGN0
name: grafana-mcp
sources:
- https://github.com/grafana/mcp-grafana
- https://github.com/grafana/helm-charts
type: application
version: 0.1.0
